# -*- coding: utf-8 -*-
"""Ecuelas de pensamiento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a7ZReKK7Pvmit7thnomKCgwbeFw3aS8Y
"""

import streamlit as st

# Título de la aplicación
st.title("Escuelas de Pensamiento Económico")

st.image("URC.png", caption="UST-URC Universidad Rosario Castellanos", width=300)


# Menú desplegable con opciones de escuelas de pensamiento económico
escuelas = [
    "Clásica",
    "Keynesiana",
    "Neoclásica",
    "Marxista",
    "Austriaca",
    "Monetarista",
    "Escuela de Chicago"
]

# Selección de la escuela de pensamiento económico
escuela_seleccionada = st.selectbox("Selecciona una escuela de pensamiento económico:", escuelas)

# Descripciones de las escuelas de pensamiento económico
descripciones = {
    "Clásica": """
        La escuela clásica, encabezada por economistas como Adam Smith y David Ricardo,
        sostiene que los mercados son autorreguladores y que la intervención del gobierno debe ser mínima.
    """,
    "Keynesiana": """
        Fundada por John Maynard Keynes, esta escuela defiende que el gobierno debe intervenir
        para estabilizar la economía mediante políticas fiscales y monetarias, especialmente en tiempos de recesión.
    """,
    "Neoclásica": """
        La escuela neoclásica se basa en el análisis marginal y la idea de que los individuos son racionales
        y maximizan su utilidad. La oferta y la demanda determinan el equilibrio en los mercados.
    """,
    "Marxista": """
        Basada en las teorías de Karl Marx, esta escuela critica el capitalismo y aboga por la lucha de clases
        como motor del cambio social y económico. Propone una transición hacia una sociedad sin clases.
    """,
    "Austriaca": """
        Esta escuela se centra en la importancia del individualismo, el mercado libre y la función empresarial.
        Economistas como Friedrich Hayek y Ludwig von Mises son sus principales exponentes.
    """,
    "Monetarista": """
        Liderada por Milton Friedman, esta escuela sostiene que la política monetaria es la principal herramienta
        para controlar la inflación y que la oferta de dinero debe ser gestionada cuidadosamente.
    """,
    "Escuela de Chicago": """
        Asociada a Milton Friedman y otros economistas de la Universidad de Chicago, defiende los mercados libres,
        la mínima intervención del gobierno y el control de la inflación a través de políticas monetarias.
    """
}

# Mostrar la descripción de la escuela seleccionada
st.write(f"### {escuela_seleccionada}")
st.write(descripciones[escuela_seleccionada])