# -*- coding: utf-8 -*-
"""Escuelas de Pensamiento Económico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a7ZReKK7Pvmit7thnomKCgwbeFw3aS8Y
"""

import streamlit as st

# Título de la aplicación
st.title("Escuelas de Pensamiento Económico")

st.image("URC.png", caption="UST-URC Universidad Rosario Castellanos", width=200)

# Menú desplegable con opciones de escuelas de pensamiento económico
escuelas = [
    "Clásica (1776 - 1870)",
    "Keynesiana (1930s - Presente)",
    "Neoclásica (1870 - Presente)",
    "Marxista (1850s - Presente)",
    "Austriaca (1870s - Presente)",
    "Monetarista (1950s - Presente)",
    "Escuela de Chicago (1950s - Presente)",
    "Institucionalismo (1890s - Presente)",
    "Economía de la Información (1970s - Presente)"
]

# Selección de la escuela de pensamiento económico
escuela_seleccionada = st.selectbox("Selecciona una escuela de pensamiento económico:", escuelas)

# Descripciones de las escuelas de pensamiento económico
descripciones = {
    "Clásica (1776 - 1870)": """
        La escuela clásica, encabezada por economistas como Adam Smith y David Ricardo,
        sostiene que los mercados son autorreguladores y que la intervención del gobierno debe ser mínima.
        Surgió en el siglo XVIII con la publicación de *La riqueza de las naciones* (1776)
        de Adam Smith [DIvisión del  trabajo, Egoismo de los empresarios, Mano invisible, seguridad al empresario],
        y dominó hasta finales del siglo XIX.
    """,
    "Keynesiana (1930s - Presente)": """
        Fundada por John Maynard Keynes en respuesta a la Gran Depresión de los años 1930,
        esta escuela defiende que el gobierno debe intervenir para estabilizar la economía mediante
        políticas fiscales y monetarias, especialmente en tiempos de recesión. Su obra más influyente es
        *La Teoría General del Empleo, el Interés y el Dinero* (1936).
        Factores que afectan la Propensión Marginal del Consumo:
        Factores objetivos:

        Un cambio en la unidad de salario.

        Un cambio en la diferencia entre el ingreso bruto y el ingreso neto.

        Cambios inesperados en los valores de capital que no se han considerado en el cálculo del ingreso neto.

        Cambios en la tasa de descuento temporal.

        Cambios en la política fiscal.

        Cambios en las expectativas sobre la relación entre el nivel de ingresos presente y futuro.

        Factores subjetivos:

        Formar una reserva contra contingencias imprevistas.

        Proveer para una relación futura anticipada entre los ingresos y las necesidades del individuo o su familia diferente de la actual.

        Disfrutar de intereses y apreciación.

        Disfrutar de un gasto en aumento gradual.

        Disfrutar de una sensación de independencia y el poder de actuar.

        Asegurar una "masse de manoeuvre" para llevar a cabo proyectos especulativos o empresariales.

        Legar una fortuna.

        Satisfacer la pura avaricia, es decir, inhibiciones irracionales pero insistentes contra actos de gasto como tales.

    """,
    "Neoclásica (1870 - Presente)": """
        La escuela neoclásica surgió en la década de 1870, enfocándose en el análisis marginal
        y la idea de que los individuos son racionales y maximizan su utilidad y los empresarios maximizan su beneficio.
        La oferta y la demanda
        determinan el equilibrio en los mercados. Esta escuela sigue influyendo fuertemente en la teoría económica moderna.
    """,
    "Marxista (1850s - Presente)": """
        Basada en las teorías de Karl Marx, esta escuela critica el capitalismo y aboga por la lucha de clases
        como motor del cambio social y económico. Propone una transición hacia una sociedad sin clases.
        La obra clave es *El Capital* (1867) [Mercancia: Valor de Cambio y Valor de Uso, Trabajo socialmente necesario,
        Valor de la mercancia= c+v+p,Tasa de plusvalor=p/v, M-M, M-D-M vs D-M-D',D-D'].
        Durante una parte del proceso laboral el obrero se limita a producir el valor de su fuerza de trabajo (medios de subsistencia).
        El proceso de consumo de la fuerza de trabajo se efectua fuera de la esfera de circulación.
        La mercancia como medida de valor y tambien de circulación es el dinero.
        Aunque nació en el siglo XIX, sigue vigente en debates contemporáneos.
    """,
    "Austriaca (1870s - Presente)": """
        Esta escuela se originó en Austria a fines del siglo XIX con Carl Menger y se centra en la importancia del
        individualismo, el mercado libre y la función empresarial. Economistas como Friedrich Hayek y Ludwig von Mises
        son sus principales exponentes. Ha influido en el pensamiento económico liberal.
    """,
    "Monetarista (1950s - Presente)": """
        Liderada por Milton Friedman a partir de la década de 1950, esta escuela sostiene que la política monetaria
        es la principal herramienta para controlar la inflación y que la oferta de dinero debe ser gestionada cuidadosamente.
        El monetarismo fue influyente en las políticas económicas de los años 1970 y 1980.
    """,
    "Escuela de Chicago (1950s - Presente)": """
        Asociada a Milton Friedman y otros economistas de la Universidad de Chicago a partir de los años 1950,
        defiende los mercados libres, la mínima intervención del gobierno y el control de la inflación a través
        de políticas monetarias. Es una de las principales corrientes del pensamiento económico contemporáneo.
    """,
    "Institucionalismo (1890s - Presente)": """
        La escuela institucionalista, fundada por economistas como Thorstein Veblen y John R. Commons,
        sostiene que las instituciones sociales, políticas y económicas son cruciales para entender el comportamiento económico.
        Critica el individualismo de las teorías neoclásicas y pone énfasis en la evolución de las normas y reglas que guían las economías.
        Surgió a finales del siglo XIX y sigue siendo influyente en campos como la economía del desarrollo y la economía política.
    """,
    "Economía de la Información (1970s - Presente)": """
        La economía de la información, desarrollada principalmente a partir de los trabajos de Joseph Stiglitz, George Akerlof
        y Michael Spence, estudia cómo la información imperfecta afecta el comportamiento de los mercados. Surgió en la década de 1970
        y explica fenómenos como la selección adversa y el riesgo moral. Es clave para entender problemas como los mercados de seguros
        y el desempleo.
    """
}

# Mostrar la descripción de la escuela seleccionada
st.write(f"### {escuela_seleccionada}")
st.write(descripciones[escuela_seleccionada])


# Personalización de diseño
st.markdown("""
<style>
    .stApp {
        background-color:  #da3262;
    }
    .css-1d391kg {
        color:  #faf7f8;
    }
</style>
""", unsafe_allow_html=True)

# Añadir la línea separadora
st.markdown("<hr>", unsafe_allow_html=True)

# Sección de recursos adicionales
st.header("Recursos Adicionales")
st.write("Encuesta Nacional sobre la Diversidad Sexual y de Género (ENDISEG) 2021. (ENEGI)")
st.write("https://www.inegi.org.mx/programas/endiseg/2021/#microdatos")

# Añadir la línea separadora
st.markdown("<hr>", unsafe_allow_html=True)

# Insertar el código HTML con estilos personalizados
st.markdown("""
    <div class="container col-sm-5 creditos text-center">
        <p style="margin-top:0;margin-bottom:0;font-size:15px;color: #424040;text-align:center">
            <strong>Colaboración:</strong>
        </p>
        <p style="margin-top:0;margin-bottom:0;font-size:12px;color:  #979394 ;text-align:center">
            <strong>Asignatura (UCA): Fundamentos de la Economía  LCFI-URC</strong>
        </p>
        <p style="margin-top:0;margin-bottom:0;font-size:12px;color:  #979394 ;text-align:center">
            <strong>Grupos 106 y 107 COY-LCFI-URC</strong>
        </p>
    </div>
""", unsafe_allow_html=True)